// Code generated by MockGen. DO NOT EDIT.
// Source: example/layered-architecture/services (interfaces: ServiceInterface)

// Package services is a generated GoMock package.
package services

import (
	models "example/layered-architecture/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// AddFollowee mocks base method.
func (m *MockServiceInterface) AddFollowee(arg0 *models.Follows) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFollowee", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFollowee indicates an expected call of AddFollowee.
func (mr *MockServiceInterfaceMockRecorder) AddFollowee(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFollowee", reflect.TypeOf((*MockServiceInterface)(nil).AddFollowee), arg0)
}

// AddTweet mocks base method.
func (m *MockServiceInterface) AddTweet(arg0 *models.Tweet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTweet", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTweet indicates an expected call of AddTweet.
func (mr *MockServiceInterfaceMockRecorder) AddTweet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTweet", reflect.TypeOf((*MockServiceInterface)(nil).AddTweet), arg0)
}

// AddUser mocks base method.
func (m *MockServiceInterface) AddUser(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockServiceInterfaceMockRecorder) AddUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockServiceInterface)(nil).AddUser), arg0)
}

// CheckFollowing mocks base method.
func (m *MockServiceInterface) CheckFollowing(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckFollowing", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckFollowing indicates an expected call of CheckFollowing.
func (mr *MockServiceInterfaceMockRecorder) CheckFollowing(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFollowing", reflect.TypeOf((*MockServiceInterface)(nil).CheckFollowing), arg0, arg1)
}

// DeleteFollowee mocks base method.
func (m *MockServiceInterface) DeleteFollowee(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteFollowee", arg0, arg1)
}

// DeleteFollowee indicates an expected call of DeleteFollowee.
func (mr *MockServiceInterfaceMockRecorder) DeleteFollowee(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFollowee", reflect.TypeOf((*MockServiceInterface)(nil).DeleteFollowee), arg0, arg1)
}

// DeleteTweet mocks base method.
func (m *MockServiceInterface) DeleteTweet(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteTweet", arg0)
}

// DeleteTweet indicates an expected call of DeleteTweet.
func (mr *MockServiceInterfaceMockRecorder) DeleteTweet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTweet", reflect.TypeOf((*MockServiceInterface)(nil).DeleteTweet), arg0)
}

// GetAllUsers mocks base method.
func (m *MockServiceInterface) GetAllUsers() *[]models.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers")
	ret0, _ := ret[0].(*[]models.User)
	return ret0
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockServiceInterfaceMockRecorder) GetAllUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockServiceInterface)(nil).GetAllUsers))
}

// GetFolloweesOfUser mocks base method.
func (m *MockServiceInterface) GetFolloweesOfUser(arg0 string) *[]models.Follows {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolloweesOfUser", arg0)
	ret0, _ := ret[0].(*[]models.Follows)
	return ret0
}

// GetFolloweesOfUser indicates an expected call of GetFolloweesOfUser.
func (mr *MockServiceInterfaceMockRecorder) GetFolloweesOfUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolloweesOfUser", reflect.TypeOf((*MockServiceInterface)(nil).GetFolloweesOfUser), arg0)
}

// GetTweetsOfUser mocks base method.
func (m *MockServiceInterface) GetTweetsOfUser(arg0 string) *[]models.Tweet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTweetsOfUser", arg0)
	ret0, _ := ret[0].(*[]models.Tweet)
	return ret0
}

// GetTweetsOfUser indicates an expected call of GetTweetsOfUser.
func (mr *MockServiceInterfaceMockRecorder) GetTweetsOfUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTweetsOfUser", reflect.TypeOf((*MockServiceInterface)(nil).GetTweetsOfUser), arg0)
}

// SignIn mocks base method.
func (m *MockServiceInterface) SignIn(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignIn indicates an expected call of SignIn.
func (mr *MockServiceInterfaceMockRecorder) SignIn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockServiceInterface)(nil).SignIn), arg0)
}
